# Generated by Django 3.2.14 on 2022-07-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_type',
            new_name='moderator',
        ),
    ]
